# Generated by Django 6.0.1 on 2026-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
