# Generated by Django 6.0.1 on 2026-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Email',
            field=models.CharField(default=' ', max_length=90),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(default='', max_length=90),
        ),
    ]
