# Generated by Django 6.0.1 on 2026-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_email_orders_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Email',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=90),
        ),
    ]
